// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Models;

namespace ToDoApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20191208211553_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoApi.Models.TodoItem", b =>
                {
                    b.Property<int>("TodoItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TaskName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TodoItemID");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("TodoApi.Models.TodoSubItem", b =>
                {
                    b.Property<int>("TodoSubItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubTaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTaskName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTaskStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TodoItemID")
                        .HasColumnType("int");

                    b.HasKey("TodoSubItemID");

                    b.HasIndex("TodoItemID");

                    b.ToTable("TodoSubItems");
                });

            modelBuilder.Entity("TodoApi.Models.TodoSubItem", b =>
                {
                    b.HasOne("TodoApi.Models.TodoItem", null)
                        .WithMany("TodoSubItems")
                        .HasForeignKey("TodoItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
